#!/usr/bin/env bash
# cc-launch — unified installer
#
# Modes:
#   [1] Always-on  — cc-launch runs on every new terminal tab (default)
#   [2] On-demand  — cc-launch only runs via a terminal keyboard shortcut
#
# Every file modified is backed up as <file>.cc-launch.bak before touching it.
# A manifest is written to ~/.claude/cc-launch-manifest.json for uninstall.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Markers that wrap every block we append — used by uninstaller to find+remove
BLOCK_START="# >>> cc-launch >>>"
BLOCK_END="# <<< cc-launch <<<"

# Manifest tracking (populated throughout, written at end)
MANIFEST_MODIFIED=()   # files we appended to
MANIFEST_CREATED=()    # files we created from scratch
MANIFEST_BACKUPS=()    # "original:backup" pairs

echo ""
echo "╭─────────────────────────────────────────────────────────────────╮"
echo "│                cc-launch — Claude Code Launcher                   │"
echo "╰─────────────────────────────────────────────────────────────────╯"
echo ""

# ── OS detection ───────────────────────────────────────────────────────────────
OS_MACOS=false; OS_LINUX=false; OS_WSL=false; OS_WINDOWS=false
case "$OSTYPE" in
  darwin*)     OS_MACOS=true ;;
  linux*)      OS_LINUX=true; grep -qi "microsoft" /proc/version 2>/dev/null && OS_WSL=true ;;
  msys|cygwin) OS_WINDOWS=true ;;
esac

if $OS_WINDOWS; then
  BIN_DIR="${USERPROFILE}/.local/bin"
  CONFIG="${USERPROFILE}/.claude/cc-launch.conf"
  MANIFEST="${USERPROFILE}/.claude/cc-launch-manifest.json"
  DEFAULT_ROOT="${USERPROFILE}/projects"
else
  BIN_DIR="$HOME/.local/bin"
  CONFIG="$HOME/.claude/cc-launch.conf"
  MANIFEST="$HOME/.claude/cc-launch-manifest.json"
  DEFAULT_ROOT="$HOME/projects"
fi

# ── Helpers ────────────────────────────────────────────────────────────────────

# Back up a file as <file>.cc-launch.bak (only if backup doesn't exist yet)
backup_file() {
  local file="$1"
  local backup="${file}.cc-launch.bak"
  if [[ -f "$file" ]] && [[ ! -f "$backup" ]]; then
    cp "$file" "$backup"
    echo "  backed up → ${backup##*/home/*/}"
    MANIFEST_BACKUPS+=("$file:::$backup")
  fi
}

# Append a block wrapped in start/end markers, tracking the file in the manifest
append_block() {
  local file="$1"
  local content="$2"
  backup_file "$file"
  printf '\n%s\n%s\n%s\n' "$BLOCK_START" "$content" "$BLOCK_END" >> "$file"
  MANIFEST_MODIFIED+=("$file")
}

# Record a file as created by us
track_created() {
  MANIFEST_CREATED+=("$1")
}

# Get PowerShell profile path as POSIX
pwsh_profile_path() {
  local path
  path="$($PWSH_EXE -NoProfile -Command '$PROFILE' 2>/dev/null)"
  $OS_WINDOWS && path="$(cygpath -u "$path" 2>/dev/null || echo "$path")"
  $OS_WSL     && path="$(wslpath  "$path" 2>/dev/null || echo "$path")"
  echo "$path"
}

# ── Mode selection ─────────────────────────────────────────────────────────────
echo "  How do you use your terminal?"
echo ""
echo "  [1] Mostly for Claude  — open picker on every new tab  (recommended)"
echo "  [2] Mixed use          — only open picker with a keyboard shortcut"
echo ""
read -rp "  Choose [1]: " MODE
MODE="${MODE:-1}"
[[ "$MODE" != "1" && "$MODE" != "2" ]] && { echo "  Invalid — defaulting to 1"; MODE="1"; }
echo ""

# ── Configuration ──────────────────────────────────────────────────────────────
read -rp "  Projects root directory [$DEFAULT_ROOT]: " INPUT_ROOT
PROJECTS_ROOT="${INPUT_ROOT:-$DEFAULT_ROOT}"
# Expand ~ manually so -d test works
PROJECTS_ROOT="${PROJECTS_ROOT/#\~/$HOME}"

if [[ ! -d "$PROJECTS_ROOT" ]]; then
  echo ""
  echo "  ⚠ Directory does not exist: $PROJECTS_ROOT"
  read -rp "  Create it now? [Y/n]: " CREATE_DIR
  if [[ "${CREATE_DIR:-Y}" =~ ^[Yy]$ ]]; then
    mkdir -p "$PROJECTS_ROOT"
    echo "  ✓ Created: $PROJECTS_ROOT"
  else
    echo "  Aborting — PROJECTS_ROOT must exist before installing."
    exit 1
  fi
fi
echo ""

read -rp "  Search depth (1 = top-level only, 2 = include subdirs) [2]: " INPUT_DEPTH
DEPTH="${INPUT_DEPTH:-2}"
if ! [[ "$DEPTH" =~ ^[0-9]+$ ]] || [[ "$DEPTH" -lt 1 ]]; then
  echo "  ⚠ Invalid depth — using 2"; DEPTH=2
fi
echo ""

read -rp "  Skip permissions prompts? --dangerously-skip-permissions [y/N]: " INPUT_SKIP
SKIP_PERMISSIONS=false
[[ "${INPUT_SKIP:-N}" =~ ^[Yy]$ ]] && SKIP_PERMISSIONS=true
echo ""

read -rp "  Always resume last session? --continue [y/N]: " INPUT_RESUME
RESUME_SESSION=false
[[ "${INPUT_RESUME:-N}" =~ ^[Yy]$ ]] && RESUME_SESSION=true
echo ""

# ── Write config ───────────────────────────────────────────────────────────────
mkdir -p "$(dirname "$CONFIG")"
[[ -f "$CONFIG" ]] && backup_file "$CONFIG"
cat > "$CONFIG" <<EOF
# cc-launch configuration — generated by install-picker.sh
PROJECTS_ROOT="$PROJECTS_ROOT"
DEPTH=$DEPTH
SKIP_PERMISSIONS=$SKIP_PERMISSIONS
RESUME_SESSION=$RESUME_SESSION
EOF
track_created "$CONFIG"
echo "→ Config: PROJECTS_ROOT=$PROJECTS_ROOT  DEPTH=$DEPTH  SKIP_PERMISSIONS=$SKIP_PERMISSIONS  RESUME_SESSION=$RESUME_SESSION"

# ── Install binary ─────────────────────────────────────────────────────────────
mkdir -p "$BIN_DIR"
cp "$SCRIPT_DIR/cc-launch.sh" "$BIN_DIR/cc-launch"
chmod +x "$BIN_DIR/cc-launch"
track_created "$BIN_DIR/cc-launch"
echo "→ Installed: $BIN_DIR/cc-launch"

if ! echo "$PATH" | grep -q "$BIN_DIR"; then
  echo "  ⚠ $BIN_DIR not in PATH — add to your shell RC:"
  echo "    export PATH=\"$BIN_DIR:\$PATH\""
fi
echo ""

# ── Shell detection ────────────────────────────────────────────────────────────
HAS_ZSH=false;  command -v zsh  &>/dev/null && HAS_ZSH=true
HAS_BASH=false; command -v bash &>/dev/null && HAS_BASH=true
HAS_FISH=false; command -v fish &>/dev/null && HAS_FISH=true
HAS_PWSH=false; PWSH_EXE=""
if   command -v pwsh       &>/dev/null; then HAS_PWSH=true; PWSH_EXE="pwsh"
elif command -v powershell &>/dev/null; then HAS_PWSH=true; PWSH_EXE="powershell"; fi

# ── Helper: install RC hook ────────────────────────────────────────────────────
install_rc_hook() {
  local shell_name="$1"
  local rc_file="$2"
  local hook_content="$3"
  mkdir -p "$(dirname "$rc_file")"
  if grep -qF "$BLOCK_START" "$rc_file" 2>/dev/null; then
    echo "→ $shell_name: already installed"
  else
    append_block "$rc_file" "$hook_content"
    echo "→ $shell_name: installed ($rc_file)"
  fi
}

# ══════════════════════════════════════════════════════════════════════════════
# MODE 1 — Always-on
# ══════════════════════════════════════════════════════════════════════════════
if [[ "$MODE" == "1" ]]; then
  echo "── Mode: every new tab ───────────────────────────────────────────────"
  echo ""

  $HAS_ZSH  && install_rc_hook "zsh"  "$HOME/.zshrc" \
'# Opens the Claude Code project picker on every new interactive shell
# Uses zle-line-init (fires after all precmds, incl. Powerlevel10k finalizer)
if [[ $- == *i* ]]; then
  _cc_launch_once() {
    _cc_launch_once() {}  # redefine as no-op so ZLE can call zle-line-init again
    zle -I               # hand off terminal control before running interactive program
    cc-launch
  }
  zle -N zle-line-init _cc_launch_once
fi'

  $HAS_BASH && install_rc_hook "bash" "$HOME/.bashrc" \
'# Opens the Claude Code project picker on every new interactive shell
if [[ $- == *i* ]]; then cc-launch; fi'

  $HAS_FISH && install_rc_hook "fish" "$HOME/.config/fish/config.fish" \
'# Opens the Claude Code project picker on every new interactive shell
if status is-interactive; cc-launch; end'

  if $HAS_PWSH; then
    PS_PROFILE="$(pwsh_profile_path)"
    install_rc_hook "pwsh" "$PS_PROFILE" \
'# Opens the Claude Code project picker on every new interactive shell
if ($Host.Name -eq "ConsoleHost") { cc-launch }'
  fi

  echo ""
  echo "  All done. Open a new terminal tab to try it."
  echo "  Tip: press ctrl+c to skip the picker and drop to a normal shell."
fi

# ══════════════════════════════════════════════════════════════════════════════
# MODE 2 — On-demand
# ══════════════════════════════════════════════════════════════════════════════
if [[ "$MODE" == "2" ]]; then
  echo "── Mode: on-demand keyboard shortcut ─────────────────────────────────"
  echo ""

  # Install claude-shell wrapper
  if $OS_WINDOWS; then
    WRAPPER="$BIN_DIR/claude-shell.ps1"
    cat > "$WRAPPER" <<'EOF'
# claude-shell.ps1 — sets CC_LAUNCH=1 and starts the shell
$env:CC_LAUNCH = "1"
$shell = if ($env:CLAUDE_SHELL) { $env:CLAUDE_SHELL } else {
    (Get-Command pwsh -ErrorAction SilentlyContinue).Source ?? "powershell"
}
& $shell
EOF
  else
    WRAPPER="$BIN_DIR/claude-shell"
    cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# claude-shell — sets CC_LAUNCH=1 and starts the shell
export CC_LAUNCH=1
exec \${CLAUDE_SHELL:-$SHELL}
EOF
    chmod +x "$WRAPPER"
  fi
  track_created "$WRAPPER"
  echo "→ Wrapper installed: $WRAPPER"
  echo ""

  $HAS_ZSH  && install_rc_hook "zsh"  "$HOME/.zshrc" \
'# Opens picker only when shell is started via the claude-shell wrapper
# Uses zle-line-init (fires after all precmds, incl. Powerlevel10k finalizer)
if [[ "$CC_LAUNCH" == "1" && $- == *i* ]]; then
  unset CC_LAUNCH
  _cc_launch_once() {
    _cc_launch_once() {}  # redefine as no-op so ZLE can call zle-line-init again
    zle -I               # hand off terminal control before running interactive program
    cc-launch
  }
  zle -N zle-line-init _cc_launch_once
fi'

  $HAS_BASH && install_rc_hook "bash" "$HOME/.bashrc" \
'# Opens picker only when shell is started via the claude-shell wrapper
if [[ "$CC_LAUNCH" == "1" && $- == *i* ]]; then
  unset CC_LAUNCH; cc-launch
fi'

  $HAS_FISH && install_rc_hook "fish" "$HOME/.config/fish/config.fish" \
'# Opens picker only when shell is started via the claude-shell wrapper
if set -q CC_LAUNCH; and test "$CC_LAUNCH" = "1"; and status is-interactive
    set -e CC_LAUNCH; cc-launch
end'

  if $HAS_PWSH; then
    PS_PROFILE="$(pwsh_profile_path)"
    install_rc_hook "pwsh" "$PS_PROFILE" \
'# Opens picker only when shell is started via the claude-shell wrapper
if ($env:CC_LAUNCH -eq "1" -and $Host.Name -eq "ConsoleHost") {
    Remove-Item Env:CC_LAUNCH; cc-launch
}'
  fi

  echo ""
  echo "  Shell hooks installed. Configuring terminal keybinds..."
  echo ""
  bash "$SCRIPT_DIR/install-cc-launch.sh"
fi

# ── Write manifest ─────────────────────────────────────────────────────────────
TIMESTAMP="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

python3 - <<PYEOF
import json, os

manifest_path = os.path.expanduser("$MANIFEST")
os.makedirs(os.path.dirname(manifest_path), exist_ok=True)

manifest = {
    "version": "1",
    "timestamp": "$TIMESTAMP",
    "mode": "$MODE",
    "modified_files": [f for f in """${MANIFEST_MODIFIED[*]:-}""".split() if f],
    "created_files":  [f for f in """${MANIFEST_CREATED[*]:-}""".split() if f],
    "backups": dict(
        pair.split(":::") for pair in """${MANIFEST_BACKUPS[*]:-}""".split()
        if ":::" in pair
    ),
}

with open(manifest_path, "w") as f:
    json.dump(manifest, f, indent=2)

print(f"→ Manifest written: {manifest_path}")
PYEOF

echo ""
echo "────────────────────────────────────────────────────────────────────"
echo "  All done! Open a new terminal tab to try it."
echo "  To uninstall: bash $SCRIPT_DIR/uninstall-picker.sh"
echo ""
