#!/usr/bin/env bash
# Install cc-launch and configure terminal shortcuts

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_NAME="cc-launch"
SCRIPT_SRC="$SCRIPT_DIR/cc-launch.sh"

# ── OS detection ───────────────────────────────────────────────────────────────
OS_MACOS=false
OS_LINUX=false
OS_WSL=false
OS_WINDOWS=false

case "$OSTYPE" in
  darwin*)
    OS_MACOS=true ;;
  linux*)
    OS_LINUX=true
    grep -qi "microsoft" /proc/version 2>/dev/null && OS_WSL=true ;;
  msys|cygwin)
    OS_WINDOWS=true ;;
esac

# ── Platform-aware paths ───────────────────────────────────────────────────────
if $OS_WINDOWS; then
  BIN_DIR="${USERPROFILE}/.local/bin"
  CONFIG="${CC_LAUNCH_CONFIG:-${USERPROFILE}/.claude/cc-launch.conf}"
  DEFAULT_ROOT="${USERPROFILE}/projects"
else
  BIN_DIR="$HOME/.local/bin"
  CONFIG="${CC_LAUNCH_CONFIG:-$HOME/.claude/cc-launch.conf}"
  DEFAULT_ROOT="~/projects"
fi

SCRIPT_DST="$BIN_DIR/$SCRIPT_NAME"

# ── 1. Configuration prompts ───────────────────────────────────────────────────
echo "╭─ Claude Pick Setup ─────────────────────────────────────────────╮"
echo "│  Configure your project picker                                  │"
echo "╰─────────────────────────────────────────────────────────────────╯"
echo ""

read -rp "  Projects root directory [$DEFAULT_ROOT]: " INPUT_ROOT
PROJECTS_ROOT="${INPUT_ROOT:-$DEFAULT_ROOT}"

read -rp "  Search depth (1 = top-level only, 2 = one level deep) [2]: " INPUT_DEPTH
DEPTH="${INPUT_DEPTH:-2}"

if ! [[ "$DEPTH" =~ ^[0-9]+$ ]] || [[ "$DEPTH" -lt 1 ]]; then
  echo "  ⚠ Invalid depth — using 2"
  DEPTH=2
fi

echo ""

# ── 2. Write config ────────────────────────────────────────────────────────────
mkdir -p "$(dirname "$CONFIG")"
cat > "$CONFIG" <<EOF
# cc-launch configuration
# Generated by install-cc-launch.sh
PROJECTS_ROOT="$PROJECTS_ROOT"
DEPTH=$DEPTH
EOF
echo "→ Config written to $CONFIG"
echo "  PROJECTS_ROOT=$PROJECTS_ROOT"
echo "  DEPTH=$DEPTH"
echo ""

# ── 3. Copy script to bin ──────────────────────────────────────────────────────
echo "→ Installing $SCRIPT_NAME to $BIN_DIR"
mkdir -p "$BIN_DIR"
cp "$SCRIPT_SRC" "$SCRIPT_DST"
chmod +x "$SCRIPT_DST"
echo "  ✓ Installed at $SCRIPT_DST"

if ! echo "$PATH" | grep -q "$BIN_DIR"; then
  echo "  ⚠ $BIN_DIR is not in PATH — add this to your shell RC:"
  echo "    export PATH=\"$BIN_DIR:\$PATH\""
fi

echo ""

# ── 4. Terminal configuration ──────────────────────────────────────────────────

# ── macOS ──────────────────────────────────────────────────────────────────────
if $OS_MACOS; then
  HAS_ITERM=false
  HAS_GHOSTTY=false
  [[ -d "/Applications/iTerm.app" ]] && HAS_ITERM=true
  [[ -d "/Applications/Ghostty.app" ]] && HAS_GHOSTTY=true

  if $HAS_ITERM; then
    echo "→ iTerm2 detected — adding 'Claude' profile"
    python3 - "$SCRIPT_DST" <<'PYEOF'
import sys, uuid, subprocess, plistlib, os, copy

PLIST = os.path.expanduser("~/Library/Preferences/com.googlecode.iterm2.plist")
CMD = sys.argv[1]
PROFILE_NAME = "Claude"
SHORTCUT_KEY = "0x63-0x140000"  # cmd+ctrl+c

result = subprocess.run(["plutil", "-convert", "xml1", "-o", "-", PLIST], capture_output=True)
prefs = plistlib.loads(result.stdout)
profiles = prefs.get("New Bookmarks", [])

existing = next((p for p in profiles if p.get("Name") == PROFILE_NAME), None)
if existing:
    print(f"  ✓ Profile '{PROFILE_NAME}' already exists (skipping)")
    profile_guid = existing["Guid"]
else:
    default = next((p for p in profiles if p.get("Default Bookmark", "No") == "Yes"), profiles[0] if profiles else {})
    profile = copy.deepcopy(default)
    profile_guid = str(uuid.uuid4()).upper()
    profile["Name"] = PROFILE_NAME
    profile["Guid"] = profile_guid
    profile["Custom Command"] = "Yes"
    profile["Command"] = CMD
    profile["Default Bookmark"] = "No"
    profile["Badge Text"] = ""
    profiles.append(profile)
    prefs["New Bookmarks"] = profiles
    print(f"  ✓ Created profile '{PROFILE_NAME}' (guid: {profile_guid})")

key_map = prefs.get("Global Key Map", {})
if SHORTCUT_KEY in key_map:
    print(f"  ⚠ Shortcut cmd+ctrl+c already bound — skipping keybind")
else:
    key_map[SHORTCUT_KEY] = {"Action": 25, "Text": profile_guid, "Version": 1}
    prefs["Global Key Map"] = key_map
    print(f"  ✓ Bound cmd+ctrl+c → New Tab with '{PROFILE_NAME}'")

xml = plistlib.dumps(prefs, fmt=plistlib.FMT_XML)
subprocess.run(["plutil", "-convert", "binary1", "-o", PLIST, "-"], input=xml, check=True)
print("  ✓ iTerm2 preferences saved — restart iTerm2 to apply")
PYEOF
    echo ""
  fi

  if $HAS_GHOSTTY; then
    echo "→ Ghostty detected (macOS)"
    GHOSTTY_CONFIG="$HOME/.config/ghostty/config"
    mkdir -p "$(dirname "$GHOSTTY_CONFIG")"
    MARKER="# cc-launch shortcut"
    if grep -q "$MARKER" "$GHOSTTY_CONFIG" 2>/dev/null; then
      echo "  ✓ Ghostty keybind already present (skipping)"
    else
      cat >> "$GHOSTTY_CONFIG" <<EOF

$MARKER
# Opens a new tab — shell auto-runs cc-launch via CC_LAUNCH env var
keybind = ctrl+cmd+c=new_tab
EOF
      echo "  ✓ Added ctrl+cmd+c → new tab keybind"
    fi
    echo ""
  fi
fi

# ── Linux ──────────────────────────────────────────────────────────────────────
if $OS_LINUX; then
  WRAPPER="$BIN_DIR/claude-shell"

  # ── Ghostty (Linux) ────────────────────────────────────────────────────────
  HAS_GHOSTTY=false
  command -v ghostty &>/dev/null && HAS_GHOSTTY=true
  [[ -d "$HOME/.config/ghostty" ]] && HAS_GHOSTTY=true

  if $HAS_GHOSTTY; then
    echo "→ Ghostty detected (Linux)"
    GHOSTTY_CONFIG="$HOME/.config/ghostty/config"
    mkdir -p "$(dirname "$GHOSTTY_CONFIG")"
    MARKER="# cc-launch shortcut"
    if grep -q "$MARKER" "$GHOSTTY_CONFIG" 2>/dev/null; then
      echo "  ✓ Ghostty config already present (skipping)"
    else
      GHOSTTY_BIN="$(command -v ghostty 2>/dev/null || echo "ghostty")"
      cat >> "$GHOSTTY_CONFIG" <<EOF

$MARKER
# Opens a new tab — shell auto-runs cc-launch via CC_LAUNCH env var
keybind = super+ctrl+c=new_tab
EOF
      echo "  ✓ Added super+ctrl+c → new tab keybind"
    fi

    # .desktop launcher for app menus / global shortcuts
    DESKTOP_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
    DESKTOP_FILE="$DESKTOP_DIR/claude-shell.desktop"
    mkdir -p "$DESKTOP_DIR"
    if [[ -f "$DESKTOP_FILE" ]]; then
      echo "  ✓ .desktop launcher already exists (skipping)"
    else
      GHOSTTY_BIN="$(command -v ghostty 2>/dev/null || echo "ghostty")"
      cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Name=Claude Shell
Comment=Open a terminal with cc-launch auto-launched
Exec=$GHOSTTY_BIN -e $WRAPPER
Icon=terminal
Terminal=false
Type=Application
Categories=Development;
EOF
      echo "  ✓ Created .desktop launcher: $DESKTOP_FILE"
      echo "  Tip: assign a global shortcut to 'Claude Shell' in your DE settings"
    fi
    echo ""
  fi

  # ── Kitty ──────────────────────────────────────────────────────────────────
  HAS_KITTY=false
  command -v kitty &>/dev/null && HAS_KITTY=true
  [[ -f "$HOME/.config/kitty/kitty.conf" ]] && HAS_KITTY=true

  if $HAS_KITTY; then
    echo "→ Kitty detected"
    KITTY_CONF="$HOME/.config/kitty/kitty.conf"
    mkdir -p "$(dirname "$KITTY_CONF")"
    MARKER_KITTY="# cc-launch shortcut"
    if grep -q "$MARKER_KITTY" "$KITTY_CONF" 2>/dev/null; then
      echo "  ✓ Kitty keybind already present (skipping)"
    else
      cat >> "$KITTY_CONF" <<EOF

$MARKER_KITTY
# Opens a new tab running claude-shell (sets CC_LAUNCH=1)
map super+ctrl+c launch --type=tab $WRAPPER
EOF
      echo "  ✓ Added super+ctrl+c → new tab keybind"
    fi
    echo ""
  fi

  # ── WezTerm ────────────────────────────────────────────────────────────────
  HAS_WEZTERM=false
  command -v wezterm &>/dev/null && HAS_WEZTERM=true
  [[ -f "$HOME/.wezterm.lua" ]] && HAS_WEZTERM=true

  if $HAS_WEZTERM; then
    echo "→ WezTerm detected"
    WEZTERM_CONF="$HOME/.wezterm.lua"
    MARKER_WEZ="-- cc-launch shortcut"
    if grep -q "$MARKER_WEZ" "$WEZTERM_CONF" 2>/dev/null; then
      echo "  ✓ WezTerm keybind already present (skipping)"
    else
      cat >> "$WEZTERM_CONF" <<EOF

$MARKER_WEZ
-- Opens a new tab with CC_LAUNCH=1 (auto-launches project picker)
-- Requires 'config' table to be defined above this block.
table.insert(config.keys, {
  key = 'c',
  mods = 'SUPER|CTRL',
  action = require('wezterm').action.SpawnCommandInNewTab {
    args = { '$WRAPPER' },
  },
})
EOF
      echo "  ✓ Added super+ctrl+c → new tab keybind to $WEZTERM_CONF"
      echo "  ⚠ Ensure 'config' is defined before this block in your wezterm.lua"
    fi
    echo ""
  fi

  # ── Alacritty ──────────────────────────────────────────────────────────────
  if command -v alacritty &>/dev/null; then
    echo "→ Alacritty detected"
    echo "  ⚠ Alacritty doesn't support 'open new tab with command' via keybind."
    echo "  Launch it directly with:  alacritty -e $WRAPPER"
    echo "  Or bind that command in your desktop environment's keyboard settings."
    echo ""
  fi
fi

# ── Windows Terminal (Windows or WSL) ─────────────────────────────────────────
if $OS_WINDOWS || $OS_WSL; then
  if $OS_WSL; then
    WIN_APPDATA="$(cmd.exe /C "echo %LOCALAPPDATA%" 2>/dev/null | tr -d '\r')"
    WT_SETTINGS="$(wslpath "$WIN_APPDATA")/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"
    WRAPPER_WIN="$(wslpath -w "$BIN_DIR/claude-shell.ps1" 2>/dev/null || echo "$BIN_DIR/claude-shell.ps1")"
  else
    WT_SETTINGS="$(cygpath -u "$LOCALAPPDATA")/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"
    WRAPPER_WIN="$(cygpath -w "$BIN_DIR/claude-shell.ps1" 2>/dev/null || echo "$BIN_DIR/claude-shell.ps1")"
  fi

  if [[ -f "$WT_SETTINGS" ]]; then
    echo "→ Windows Terminal detected — adding 'Claude' profile"
    python3 - "$WT_SETTINGS" "$WRAPPER_WIN" <<'PYEOF'
import sys, json, uuid

settings_path = sys.argv[1]
cmd = sys.argv[2]

try:
    with open(settings_path, 'r', encoding='utf-8-sig') as f:
        settings = json.load(f)
except json.JSONDecodeError:
    print("  ⚠ settings.json has comments or is invalid JSON — skipping")
    print("  Add a 'Claude' profile manually with commandline: pwsh -NoExit -File \"" + cmd + "\"")
    sys.exit(0)

profiles_list = settings.get("profiles", {}).get("list", [])
existing = next((p for p in profiles_list if p.get("name") == "Claude"), None)

if existing:
    print("  ✓ Profile 'Claude' already exists (skipping)")
else:
    profiles_list.append({
        "name": "Claude",
        "guid": "{" + str(uuid.uuid4()) + "}",
        "commandline": f'pwsh -NoExit -File "{cmd}"',
        "hidden": False,
    })
    settings.setdefault("profiles", {})["list"] = profiles_list

    with open(settings_path, 'w', encoding='utf-8') as f:
        json.dump(settings, f, indent=4)
    print("  ✓ Created 'Claude' profile — restart Windows Terminal to apply")
PYEOF
    echo ""
  else
    echo "→ Windows Terminal not found — skipping WT profile"
    echo ""
  fi
fi

echo "Done."
