#Requires -Version 5.1
# install-windows.ps1
# Native Windows installer for cc-launch
# Run with: pwsh -ExecutionPolicy Bypass -File install-windows.ps1

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$BinDir = "$env:USERPROFILE\.local\bin"
$ConfigDir = "$env:USERPROFILE\.claude"
$BlockStart = "# >>> cc-launch >>>"
$BlockEnd   = "# <<< cc-launch <<<"

Write-Host ""
Write-Host "╭─────────────────────────────────────────────────────────────────╮"
Write-Host "│                cc-launch — Claude Code Launcher                   │"
Write-Host "╰─────────────────────────────────────────────────────────────────╯"
Write-Host ""

# ── 1. Ensure bin dir exists and is in PATH ────────────────────────────────────
if (-not (Test-Path $BinDir)) { New-Item -ItemType Directory -Path $BinDir | Out-Null }
$currentPath = [Environment]::GetEnvironmentVariable("PATH", "User")
if ($currentPath -notlike "*$BinDir*") {
    [Environment]::SetEnvironmentVariable("PATH", "$currentPath;$BinDir", "User")
    Write-Host "→ Added $BinDir to user PATH (restart shell to take effect)"
}

# ── 2. Mode selection ──────────────────────────────────────────────────────────
Write-Host "  How do you use your terminal?"
Write-Host ""
Write-Host "  [1] Mostly for Claude  — open picker on every new tab  (recommended)"
Write-Host "  [2] Mixed use          — only open picker with a keyboard shortcut"
Write-Host ""
$Mode = Read-Host "  Choose [1]"
if ([string]::IsNullOrWhiteSpace($Mode)) { $Mode = "1" }
if ($Mode -ne "1" -and $Mode -ne "2") { Write-Host "  Invalid — defaulting to 1"; $Mode = "1" }
Write-Host ""

# ── 3. Configuration ───────────────────────────────────────────────────────────
$DefaultRoot = "$env:USERPROFILE\projects"
$InputRoot = Read-Host "  Projects root directory [$DefaultRoot]"
if ([string]::IsNullOrWhiteSpace($InputRoot)) { $InputRoot = $DefaultRoot }

if (-not (Test-Path $InputRoot)) {
    Write-Host ""
    Write-Host "  ⚠ Directory does not exist: $InputRoot"
    $Create = Read-Host "  Create it now? [Y/n]"
    if ([string]::IsNullOrWhiteSpace($Create) -or $Create -match '^[Yy]') {
        New-Item -ItemType Directory -Path $InputRoot | Out-Null
        Write-Host "  ✓ Created: $InputRoot"
    } else {
        Write-Host "  Aborting — PROJECTS_ROOT must exist before installing."
        exit 1
    }
}

$InputDepth = Read-Host "  Search depth (1 = top-level only, 2 = include subdirs) [2]"
if ([string]::IsNullOrWhiteSpace($InputDepth)) { $InputDepth = "2" }
if (-not ($InputDepth -match '^\d+$') -or [int]$InputDepth -lt 1) {
    Write-Host "  ⚠ Invalid depth — using 2"; $InputDepth = "2"
}
Write-Host ""

# ── 4. Write config ────────────────────────────────────────────────────────────
if (-not (Test-Path $ConfigDir)) { New-Item -ItemType Directory -Path $ConfigDir | Out-Null }
$ConfigPath = "$ConfigDir\cc-launch.conf"
$PosixRoot = $InputRoot -replace '\\', '/'
@"
# cc-launch configuration — generated by install-windows.ps1
PROJECTS_ROOT="$PosixRoot"
DEPTH=$InputDepth
"@ | Set-Content -Path $ConfigPath -Encoding UTF8
Write-Host "→ Config: PROJECTS_ROOT=$InputRoot  DEPTH=$InputDepth"

# ── 5. Install cc-launch shim ───────────────────────────────────────────────
# cc-launch.sh runs via bash (Git Bash / WSL). Create a .ps1 shim.
$ClaudePickSrc = Join-Path $ScriptDir "cc-launch.sh"
$PosixSrc = $ClaudePickSrc -replace '\\', '/'
$ClaudePickDst = "$BinDir\cc-launch.ps1"
@"
# cc-launch.ps1 — calls the bash implementation via Git Bash / WSL
& bash "$PosixSrc"
"@ | Set-Content -Path $ClaudePickDst -Encoding UTF8
Write-Host "→ Installed: $ClaudePickDst"
Write-Host ""

# ── 6. Shell hook ──────────────────────────────────────────────────────────────
$ProfilePath = $PROFILE
$ProfileDir = Split-Path -Parent $ProfilePath
if (-not (Test-Path $ProfileDir)) { New-Item -ItemType Directory -Path $ProfileDir | Out-Null }
if (-not (Test-Path $ProfilePath)) { New-Item -ItemType File -Path $ProfilePath | Out-Null }

$ProfileContent = Get-Content -Path $ProfilePath -Raw -ErrorAction SilentlyContinue

if ($ProfileContent -like "*$BlockStart*") {
    Write-Host "→ pwsh profile: already installed ($ProfilePath)"
} else {
    if ($Mode -eq "1") {
        $Hook = @"

$BlockStart
# Opens the Claude Code project picker on every new interactive shell
if (`$Host.Name -eq "ConsoleHost") { cc-launch }
$BlockEnd
"@
    } else {
        $Hook = @"

$BlockStart
# Opens picker only when shell is started via the claude-shell wrapper
if (`$env:CC_LAUNCH -eq "1" -and `$Host.Name -eq "ConsoleHost") {
    Remove-Item Env:CC_LAUNCH; cc-launch
}
$BlockEnd
"@
    }
    Add-Content -Path $ProfilePath -Value $Hook
    Write-Host "→ pwsh profile: installed ($ProfilePath)"
}
Write-Host ""

# ── 7. Mode 2: install claude-shell wrapper ────────────────────────────────────
if ($Mode -eq "2") {
    $WrapperPath = "$BinDir\claude-shell.ps1"
    @'
# claude-shell.ps1 — sets CC_LAUNCH=1 and starts the shell
$env:CC_LAUNCH = "1"
$shell = if ($env:CLAUDE_SHELL) { $env:CLAUDE_SHELL } else {
    (Get-Command pwsh -ErrorAction SilentlyContinue).Source ?? "powershell"
}
& $shell
'@ | Set-Content -Path $WrapperPath -Encoding UTF8
    Write-Host "→ Wrapper installed: $WrapperPath"
    Write-Host ""

    # ── 8. Windows Terminal profile ────────────────────────────────────────────
    $WTSettings = "$env:LOCALAPPDATA\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json"
    if (-not (Test-Path $WTSettings)) {
        $WTSettings = "$env:LOCALAPPDATA\Microsoft\Windows Terminal\settings.json"
    }

    if (Test-Path $WTSettings) {
        Write-Host "→ Windows Terminal detected — adding 'Claude' profile"
        try {
            $settings = Get-Content $WTSettings -Raw | ConvertFrom-Json
            $profilesList = @($settings.profiles.list)
            $existing = $profilesList | Where-Object { $_.name -eq "Claude" }
            if ($existing) {
                Write-Host "  ✓ Profile 'Claude' already exists (skipping)"
            } else {
                $newProfile = [PSCustomObject]@{
                    name        = "Claude"
                    guid        = "{$([guid]::NewGuid())}"
                    commandline = "pwsh -NoExit -File `"$WrapperPath`""
                    hidden      = $false
                }
                $profilesList += $newProfile
                $settings.profiles.list = $profilesList
                $settings | ConvertTo-Json -Depth 20 | Set-Content $WTSettings -Encoding UTF8
                Write-Host "  ✓ Created 'Claude' profile — restart Windows Terminal to apply"
            }
        } catch {
            Write-Host "  ⚠ Could not update settings.json: $_"
            Write-Host "  Add a 'Claude' profile manually with commandline:"
            Write-Host "    pwsh -NoExit -File `"$WrapperPath`""
        }
    } else {
        Write-Host "→ Windows Terminal not found — skipping profile setup"
    }
    Write-Host ""
}

Write-Host "────────────────────────────────────────────────────────────────────"
Write-Host "  All done! Open a new terminal tab to try it."
if ($Mode -eq "2") {
    Write-Host "  Test it:  `$env:CC_LAUNCH = '1'; pwsh"
}
Write-Host ""
